language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - npm cache clean --force
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com

script:
  - docker build -t oliver79913/creditbill .
  - docker tag oliver79913/creditbill registry.heroku.com/creditbill/web
  - docker image ls
  - docker push oliver79913/creditbill
  - docker push registry.heroku.com/creditbill/web

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: creditbill
  script:
    heroku container:release web;
    docker container ps
  on:
    branch: master