language: node_js
node_js:
  - node

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com

script:
  - docker build -t oliver79913/$HEROKU_APP_NAME .
  - docker tag oliver79913/$HEROKU_APP_NAME registry.heroku.com/$HEROKU_APP_NAME/web
  - docker image ls

before_deploy:
  - docker push oliver79913/$HEROKU_APP_NAME:latest
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app: $HEROKU_APP_NAME
  script:
    heroku container:push web

# after_deploy:
#   - docker image ls